greendoor/Models/EditPhotoViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace greendoor.Models
{
    public class EditPhotoViewModel
    {
        [Display(Name = "Profile Photo")]
        [StringLength(255, ErrorMessage = "File name cannot exceed 255 characters!")]
        public string ShopPicture { get; set; }

        [Required(ErrorMessage = "Please input a shop photo!")]
        public IFormFile PhotoFile { get; set; }

        [Display(Name = "Shop Name")]
        [Required(ErrorMessage = "Please enter a name!")]
        [StringLength(50, ErrorMessage = "Name cannot exceed 50 characters!")]
        public string ShopName { get; set; }
    }
}

greendoor/Models/Shop.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace greendoor.Models
{
    public class Shop
    {
        [Display(Name = "Shop ID")]
        public int ShopID { get; set; }

        [Display(Name = "Profile Photo")]
        [StringLength(255, ErrorMessage = "File name cannot exceed 255 characters!")]
        public string ShopPicture { get; set; }

        [Display(Name = "Shop Name")]
        [Required(ErrorMessage = "Please enter a name!")]
        [StringLength(50, ErrorMessage = "Name cannot exceed 50 characters!")]
        public string ShopName { get; set; }

        [Display(Name ="Description")]
        [StringLength(250, ErrorMessage = "Description cannot exceed 250 characters!")]
        public string ShopDescription { get; set; }
        public string Zone { get; set; }
        [Display(Name ="Contact Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^[0-9]{8}$", ErrorMessage = "Please enter a 8-digit Phone Number")]
        [Required(ErrorMessage ="Contact Number must not be empty")]
        public int ContactNumber { get; set; }

        [StringLength(500, ErrorMessage = "Email cannot exceed 50 characters!")]
        [Required(ErrorMessage = "Address must not be empty")]
        public string Address { get; set; }

        [Display(Name ="Postal Code")]
        [Required(ErrorMessage ="Please enter the postal code")]
        [RegularExpression(@"^[0-9]{6}$", ErrorMessage = "Please enter a 6-digit Postal Code")]
        public int PostalCode { get; set; }

        [Display(Name ="Website URL")]
        [StringLength(300, ErrorMessage = "Email cannot exceed 300 characters!")]
        public string? WebsiteLink { get; set; }

        [Display(Name = "Social Media URL")]
        [StringLength(300, ErrorMessage = "Email cannot exceed 300 characters!")]
        public string? SocialMediaLink { get; set; }

        [Display(Name = "E-mail Address")]
        [EmailAddress]
        // Custom Validation Attribute for checking email address exists
        [ValidateEmailExists]
        [Required(ErrorMessage = "Please enter an email address!")]
        [StringLength(50, ErrorMessage = "Email cannot exceed 50 characters!")]
        public string EmailAddr { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please enter a password!")]
        [StringLength(255, ErrorMessage = "Password cannot exceed 255 characters!")]
        public string Password { get; set; }
        public bool IsVerified { get; set; }
        public string searchQuery { get; set; }
        public string zoneSelected { get; set; }
        public List<Shop> searchResultsList { get; set; }
        public Shop()
        {
            searchResultsList = new List<Shop>();
        }
    }
}

greendoor/Models/ShopProfileViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace greendoor.Models
{
    public class ShopProfileViewModel
    {
        [Required(ErrorMessage = "Please input a shop photo!")]
        public IFormFile PhotoFile { get; set; }

        [Display(Name = "Profile Photo")]
        [StringLength(255, ErrorMessage = "File name cannot exceed 255 characters!")]
        public string ShopPicture { get; set; }

        [Display(Name = "Shop Name")]
        [Required(ErrorMessage = "Please enter a name!")]
        [StringLength(50, ErrorMessage = "Name cannot exceed 50 characters!")]
        public string ShopName { get; set; }

        [Display(Name = "Description")]
        [StringLength(250, ErrorMessage = "Description cannot exceed 250 characters!")]
        public string ShopDescription { get; set; }
        public string Zone { get; set; }
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^[0-9]{8}$", ErrorMessage = "Please enter a 8-digit Phone Number")]
        [Required(ErrorMessage = "Contact Number must not be empty")]
        public int ContactNumber { get; set; }

        [Required(ErrorMessage = "Address must not be empty")]
        public string Address { get; set; }

        [Display(Name = "Postal Code")]
        [Required(ErrorMessage = "Please enter the postal code")]
        [RegularExpression(@"^[0-9]{6}$", ErrorMessage = "Please enter a 6-digit Postal Code")]
        public int PostalCode { get; set; }

        [Url(ErrorMessage = "Please enter an Url link!")]
        [Display(Name = "Website URL")]
        public string? WebsiteLink { get; set; }

        [Display(Name = "Social Media URL")]
        public string? SocialMediaLink { get; set; }

        [Display(Name = "E-mail Address")]
        [EmailAddress]
        // Custom Validation Attribute for checking email address exists
        [ValidateEmailExists]
        [Required(ErrorMessage = "Please enter an email address!")]
        [StringLength(50, ErrorMessage = "Email cannot exceed 50 characters!")]
        public string EmailAddr { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please enter a password!")]
        [StringLength(255, ErrorMessage = "Password cannot exceed 255 characters!")]
        public string Password { get; set; }
    }
}

greendoor/Controllers/ShopsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using greendoor.DAL;
using greendoor.Models;
using System.IO;

namespace greendoor.Controllers
{
    public class ShopsController : Controller
    {
        private ShopDAL shopContext = new ShopDAL();
        private ReviewsDAL reviewContext = new ReviewsDAL();
        private ShopPostDAL shopPostContext = new ShopPostDAL();
        private FavouriteDAL favouriteContext = new FavouriteDAL();
        private List<string> searchShopZoneList = new List<string> { "-", "West", "Central", "East", "North", "North-East", "NA" };
        private List<SelectListItem> searchshopZoneDropDownList = new List<SelectListItem>();
        public ShopsController()
        {
            foreach (string postCat in searchShopZoneList)
            {
                searchshopZoneDropDownList.Add(
                    new SelectListItem
                    {
                        Text = postCat,
                    });
            }
        }

        public IActionResult ViewShops() // shop lsit for customer and public
        {
            ViewData["zoneSelected"] = searchshopZoneDropDownList;
            List<Shop> shopList = shopContext.GetAllShop();
            // Calculating top 3 shops in terms of number of reviews
            Dictionary<string, int> shopReviewList = new Dictionary<string, int>();
            foreach (Shop shop in shopList)
            {
                int i = reviewContext.GetNumberOfReviews(shop.ShopID);
                shopReviewList.Add(shop.ShopName, i);
            }

            int j = shopReviewList.Count();
            if (j > 3)
            {
                j = 3;
            }
            var sortedDict = (from pair in shopReviewList
                              orderby pair.Value descending
                              select pair).Take(j).ToDictionary(pair => pair.Key, pair => pair.Value);

            if (j == 3)
            {
                var first = sortedDict.First();
                ViewData["topNumberReviews1a"] = first.Key;
                ViewData["topNumberReviews1b"] = first.Value;
                sortedDict.Remove(first.Key);

                var second = sortedDict.First();
                ViewData["topNumberReviews2a"] = second.Key;
                ViewData["topNumberReviews2b"] = second.Value;
                sortedDict.Remove(second.Key);

                var third = sortedDict.First();
                ViewData["topNumberReviews3a"] = third.Key;
                ViewData["topNumberReviews3b"] = third.Value;
                sortedDict.Remove(third.Key);
            }
            else if (j == 2)
            {
                var first = sortedDict.First();
                ViewData["topNumberReviews1a"] = first.Key;
                ViewData["topNumberReviews1b"] = first.Value;
                sortedDict.Remove(first.Key);

                var second = sortedDict.First();
                ViewData["topNumberReviews2a"] = second.Key;
                ViewData["topNumberReviews2b"] = second.Value;
                sortedDict.Remove(second.Key);
            }
            else if (j == 1)
            {
                var first = sortedDict.First();
                ViewData["topNumberReviews1a"] = first.Key;
                ViewData["topNumberReviews1b"] = first.Value;
                sortedDict.Remove(first.Key);
            }

            // Calculating top 3 shops in terms of number of reviews
            Dictionary<string, int> shop2ReviewList = new Dictionary<string, int>();
            foreach (Shop shop in shopList)
            {
                int i = reviewContext.GetAverageReviewScore(shop.ShopID);
                shop2ReviewList.Add(shop.ShopName, i);
            }

            int l = shop2ReviewList.Count();
            if (l > 3)
            {
                l = 3;
            }
            var sortedDict2 = (from pair in shop2ReviewList
                               orderby pair.Value descending
                               select pair).Take(l).ToDictionary(pair => pair.Key, pair => pair.Value);

            if (l == 3)
            {
                var first = sortedDict2.First();
                ViewData["topAverageReviews1a"] = first.Key;
                ViewData["topAverageReviews1b"] = first.Value;
                sortedDict2.Remove(first.Key);

                var second = sortedDict2.First();
                ViewData["topAverageReviews2a"] = second.Key;
                ViewData["topAverageReviews2b"] = second.Value;
                sortedDict2.Remove(second.Key);

                var third = sortedDict2.First();
                ViewData["topAverageReviews3a"] = third.Key;
                ViewData["topAverageReviews3b"] = third.Value;
                sortedDict2.Remove(third.Key);
            }
            else if (l == 2)
            {
                var first = sortedDict2.First();
                ViewData["topAverageReviews1a"] = first.Key;
                ViewData["topAverageReviews1b"] = first.Value;
                sortedDict2.Remove(first.Key);

                var second = sortedDict2.First();
                ViewData["topAverageReviews2a"] = second.Key;
                ViewData["topAverageReviews2b"] = second.Value;
                sortedDict2.Remove(second.Key);
            }
            else if (l == 1)
            {
                var first = sortedDict2.First();
                ViewData["topAverageReviews1a"] = first.Key;
                ViewData["topAverageReviews1b"] = first.Value;
                sortedDict2.Remove(first.Key);
            }

            // Calculating top 3 shops in terms of number of favourites
            Dictionary<string, int> shopFavouriteList = new Dictionary<string, int>();
            foreach (Shop shop in shopList)
            {
                int i = favouriteContext.GetNumFavourite(shop.ShopID);
                shopFavouriteList.Add(shop.ShopName, i);
            }

            int n = shopFavouriteList.Count();
            if (n > 3)
            {
                n = 3;
            }
            var sortedDict3 = (from pair in shopFavouriteList
                              orderby pair.Value descending
                              select pair).Take(n).ToDictionary(pair => pair.Key, pair => pair.Value);
            if (n == 3)
            {
                var first = sortedDict3.First();
                ViewData["topNumFavourite1a"] = first.Key;
                ViewData["topNumFavourite1b"] = first.Value;
                sortedDict3.Remove(first.Key);

                var second = sortedDict3.First();
                ViewData["topNumFavourite2a"] = second.Key;
                ViewData["topNumFavourite2b"] = second.Value;
                sortedDict3.Remove(second.Key);

                var third = sortedDict3.First();
                ViewData["topNumFavourite3a"] = third.Key;
                ViewData["topNumFavourite3b"] = third.Value;
                sortedDict3.Remove(third.Key);
            }
            else if (n == 2)
            {
                var first = sortedDict3.First();
                ViewData["topNumFavourite1a"] = first.Key;
                ViewData["topNumFavourite1b"] = first.Value;
                sortedDict3.Remove(first.Key);

                var second = sortedDict3.First();
                ViewData["topNumFavourite2a"] = second.Key;
                ViewData["topNumFavourite2b"] = second.Value;
                sortedDict3.Remove(second.Key);
            }
            else if (n == 1)
            {
                var first = sortedDict3.First();
                ViewData["topNumFavourite1a"] = first.Key;
                ViewData["topNumFavourite1b"] = first.Value;
                sortedDict3.Remove(first.Key);
            }


            return View(shopList);
        }

        public IActionResult Index()  // for shops login
        {
            return View();
        }


        // GET: ShopController/Details/5
        public ActionResult ShopDetails(int id)  // for customer and public
        {
            HttpContext.Session.SetString("ShopID", id.ToString());
            //HttpContext.Session.SetString("LoginID", id.ToString());

            int? customerID = HttpContext.Session.GetInt32("LoginID");
            string shopID = HttpContext.Session.GetString("ShopID");
            //int custID = Convert.ToInt32(customerID);
            ShopReviewViewModel shopreviewVM = new ShopReviewViewModel();
            shopreviewVM.reviewsList = reviewContext.GetLatestReview(id);
            shopreviewVM.shopPostList = shopPostContext.GetLatestShopPost(id);
            if (customerID != null)
            {
                shopreviewVM.FavBool = favouriteContext.GetDetails(customerID, Convert.ToInt32(shopID));
            }
            else
            {
                shopreviewVM.FavBool = false;
            }
            //Get details of competition
            Shop shop = shopContext.GetDetails(id);
            shopreviewVM.ShopID = id;
            shopreviewVM.CustomerID = customerID;
            shopreviewVM.ShopPicture = shop.ShopPicture;
            shopreviewVM.ShopName = shop.ShopName;
            shopreviewVM.ShopDescription = shop.ShopDescription;
            shopreviewVM.Zone = shop.Zone;
            shopreviewVM.ContactNumber = shop.ContactNumber;
            shopreviewVM.Address = shop.Address;
            shopreviewVM.PostalCode = shop.PostalCode;
            shopreviewVM.SocialMediaLink = shop.SocialMediaLink;
            shopreviewVM.WebsiteLink = shop.WebsiteLink;
            //If query id not in db, redirect out
            if (shop.ShopName == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            int count = 0;
            int totalScore = 0;

greendoor/Views/Shops/AddFav.cshtml
@model greendoor.Models.ShopFav

@{
    ViewData["Title"] = "Add Favourite";
}
<br>
<h4 class="PageTitle">Add @Html.Display("ShopName") to Favourites?</h4>
<section class="holder">
    <hr />
</section>

<section class="holder">

    @*<div class="shop-border">*@
    <div class="">
        <img src="~/images/@Model.ShopPicture" style="width:250px" class="justify-content-center image-padding" />
        <br />
        <br />

        @if (Context.Session.GetString("Role") == "Customer")
        {
            if (Model.FavBool == false)
            {
                <form asp-action="AddFav" asp-controller="Shops">
                    <fieldset class="FormContent">
                        <div class="form-group review-row ">
                            <label asp-for="ShopID"
                                   class="col-sm-3 col-form-label sr-only"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="ShopID" readonly
                                       class="form-control-plaintext sr-only" />
                            </div>
                        </div>
                        <div class="form-group review-row">
                            <label asp-for="CustomerID"
                                   class="col-sm-3 col-form-label sr-only"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="CustomerID" readonly
                                       class="form-control-plaintext sr-only" />
                            </div>
                        </div>
                        <div class="form-group review-row">
                            <div class="row-sm-9">
                                <a asp-controller="Shops" asp-action="ShopDetails" asp-route-id="@Context.Session.GetString("ShopID")" type="button" class="btn btn-outline-primary" id="fav">Back</a>
                                <input type="submit" value="Add"
                                       class="btn btn-outline-success" />
                            </div>
                        </div>
                        @*<span style="color:red">@ViewData["RatingError"]</span>*@
                    </fieldset>
                </form>
                @*<a asp-controller="Shops" asp-action="AddFav" type="button" class="btn btn-outline-success" id="fav">Add to Favorites</a>*@
            }
            else
            {

                @*<a asp-controller="Shops" asp-action="ViewShops" type="button" class="btn btn-outline-danger" id="fav">Remove from Favorites</a>*@
            }

        }

        else
        {
            <hr />
            <p><a asp-action="Login" asp-controller="Home">Login </a> to add to favorites!</p>
        }
    </div>
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ShopDescription" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("ShopDescription")
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ContactNumber"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("ContactNumber")
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Address"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("Address")
            </div>

        </div>
        <div class="form-group row">
            <label asp-for="WebsiteLink"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("WebsiteLink")
            </div>
        </div>

    </fieldset>



</section>

greendoor/Views/Shops/Delete.cshtml
@model greendoor.Models.ShopReviewViewModel
@{
    ViewData["Title"] = "Delete Shop";
}

<body>
    @*<h4 class="PageTitle">Add Event</h4>
        <hr />*@
    <div class="d-flex align-content-center justify-content-center">
        <div class="card my-5 shadow" style="width:1000px">
            <h2 class="card-title card-header bg-custom navbar-dark mb-3 text-center" style="color:#f5eec2">
                Delete Shop
            </h2>
            <div class="card-body">
                <form asp-action="Delete" asp-controller="Shops">
                    @Html.ValidationSummary(true)
                    <fieldset class="FormContent">
                        <div class="form-group row">
                            <label asp-for="ShopID"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="ShopID" class="form-control form-control-plaintext" readonly />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="ShopName"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="ShopName" class="form-control form-control-plaintext" readonly />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label asp-for="ShopDescription"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="ShopDescription" class="form-control form-control-plaintext" readonly />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label asp-for="Zone"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="Zone" class="form-control-plaintext" readonly />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="ContactNumber"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="ContactNumber" class="form-control-plaintext" readonly />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="Address" class="form-control form-control-plaintext" readonly />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="PostalCode"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="PostalCode" class="form-control form-control-plaintext" readonly />
                            </div>
                        </div>
                        @if (Model.SocialMediaLink != null)
                        {
                            <div class="form-group row">
                                <label asp-for="SocialMediaLink"
                                       class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9 col-md-5">
                                    <input asp-for="SocialMediaLink" class="form-control form-control-plaintext" readonly />
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="form-group row">
                                <label asp-for="SocialMediaLink"
                                       class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9 col-md-5">
                                    <input placeholder="Not Available" class="form-control form-control-plaintext" readonly />
                                </div>
                            </div>
                        }

                        @if (Model.WebsiteLink != null)
                        {
                            <div class="form-group row">
                                <label asp-for="WebsiteLink"
                                       class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9 col-md-5">
                                    <input asp-for="WebsiteLink" class="form-control form-control-plaintext" readonly />
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="form-group row">
                                <label asp-for="WebsiteLink"
                                       class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9 col-md-5">
                                    <input placeholder="Not Available" class="form-control form-control-plaintext" readonly />
                                </div>
                            </div>
                        }

                        <div class="form-group row">
                            <label asp-for="EmailAddr"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="EmailAddr" class="form-control form-control-plaintext" readonly />
                            </div>
                        </div>


                        <div class="form-group row">
                            <div class="col-sm-9 offset-sm-3">
                                <input type="submit" value="Delete" class="btn btn-primary" />
                            </div>
                        </div>
                        <div>
                            <a asp-action="ShopProfile" asp-controller="Shops">Back to Profile</a>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div>
    </div>


</body>@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

greendoor/Views/Shops/RemoveFav.cshtml
@model greendoor.Models.ShopFav

@{
    ViewData["Title"] = "Remove Favourite";
}
<br>
<h4 class="PageTitle">Remove @Html.Display("ShopName") from Favourites?</h4>
<section class="holder">
    <hr />
</section>

<section class="holder">

    @*<div class="shop-border">*@
    <div class="">
        <img src="~/images/@Model.ShopPicture" style="width:250px" class="justify-content-center image-padding" />
        <br />
        <br />

        @if (Context.Session.GetString("Role") == "Customer")
        {
            if (Model.FavBool == false)
            {
                <form asp-action="RemoveFav" asp-controller="Shops">
                    <fieldset class="FormContent">
                        <div class="form-group review-row ">
                            <label asp-for="ShopID"
                                   class="col-sm-3 col-form-label sr-only"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="ShopID" readonly
                                       class="form-control-plaintext sr-only" />
                            </div>
                        </div>
                        <div class="form-group review-row">
                            <label asp-for="CustomerID"
                                   class="col-sm-3 col-form-label sr-only"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="CustomerID" readonly
                                       class="form-control-plaintext sr-only" />
                            </div>
                        </div>
                        <div class="form-group review-row">
                            <div class="row-sm-9">
                                <a asp-controller="Shops" asp-action="ShopDetails" asp-route-id="@Context.Session.GetString("ShopID")" type="button" class="btn btn-outline-primary" id="fav">Back</a>
                                <input type="submit" value="Remove"
                                       class="btn btn-outline-danger" />
                            </div>
                        </div>
                        @*<span style="color:red">@ViewData["RatingError"]</span>*@
                    </fieldset>
                </form>
                @*<a asp-controller="Shops" asp-action="AddFav" type="button" class="btn btn-outline-success" id="fav">Add to Favorites</a>*@
            }
            else
            {

                @*<a asp-controller="Shops" asp-action="ViewShops" type="button" class="btn btn-outline-danger" id="fav">Remove from Favorites</a>*@
            }

        }

        else
        {
            <p><a asp-action="Login" asp-controller="Home">Login </a> to remove from favourites!</p>
        }
    </div>
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ShopDescription" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("ShopDescription")
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ContactNumber"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("ContactNumber")
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Address"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("Address")
            </div>

        </div>
        <div class="form-group row">
            <label asp-for="WebsiteLink"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("WebsiteLink")
            </div>
        </div>

    </fieldset>



</section>